Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
      vb.name = 'docker-compose-vm'
      vb.memory = 2048
      vb.cpus = 1
    end
  
    # set up Docker in the new VM:
    config.vm.provision :docker
    
    # vagrant plugin install vagrant-docker-compose
    # vagrant provision
    config.vm.provision :docker_compose
  end